# CONVERT PARQUET MODEL OUTPUT TO FEATURE CLASS

In [ ]:
# arcgispro3_4clone
import geopandas as gpd
import arcpy
import os
in_parquet = r"C:\Users\akreiger\dev_repos\abdu\abdumodel\output\abdu_cn_east_wH2o.parquet"
out_fc = r"D:\ABDUBounds\model_output\abdu_model_out.gdb\abdu_cn_east_wH2o_test"

In [ ]:
df = gpd.read_parquet(in_parquet)
df.set_crs('ESRI:102008', allow_override=True, inplace=True)
df.crs

<Projected CRS: ESRI:102008>
Name: North_America_Albers_Equal_Area_Conic
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: North America - onshore and offshore: Canada - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon. United States (USA) - Alabama; Alaska (mainland); Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming.
- bounds: (-172.54, 23.81, -47.74, 86.46)
Coordinate Operation:
- name: North_America_Albers_Equal_Area_Conic
- method: Albers Equal Area
Datum: North American Datum 1983
- Ellipsoid: GRS 1980
- Prime Meridian: Greenwich

In [ ]:
df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
RangeIndex: 154 entries, 0 to 153
Data columns (total 37 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   WATERSHED_CODE                154 non-null    object
 1   WATERSHED_CODE_ha             154 non-null    float64
 2   dgr_blk                       154 non-null    object
 3   CODE                          148 non-null    object
 4   species                       148 non-null    object
 5   dud_lta                       154 non-null    float64
 6   demand_lta_kcal               154 non-null    float64
 7   popobj_lta                    154 non-null    float64
 8   dud_80th                      154 non-null    float64
 9   demand_80th_kcal              154 non-null    float64
 10  popobj_80th                   154 non-null    float64
 11  tothabitat_kcal               154 non-null    float64
 12  protected_kcal                154 non-null    float64
 13  protectedhabitat_ha           154 non-null    float64
 14  urbanHa                       154 non-null    float64
 15  urbanNrgy                     154 non-null    float64
 16  unavailha                     154 non-null    float64
 17  WATERSHED_CODE_ha_unavailha   154 non-null    float64
 18  surpdef_lta_kcal              154 non-null    float64
 19  surpdef_80th_kcal             154 non-null    float64
 20  geometry                      154 non-null    geometry
 21  nrgprot_lta_kcal              154 non-null    float64
 22  nrgprot_80th_kcal             154 non-null    float64
 23  WATERSHED_CODE_1              154 non-null    object
 24  DeepwaterFresh                154 non-null    float64
 25  FreshMarsh                    154 non-null    float64
 26  FreshShallowOpenWater         154 non-null    float64
 27  FreshwaterWoody               154 non-null    float64
 28  ManagedFreshMarsh             154 non-null    float64
 29  ManagedFreshShallowOpenWater  154 non-null    float64
 30  ManagedFreshwaterAquaticBed   154 non-null    float64
 31  wtMean_kcal_per_ha            154 non-null    float64
 32  available_ha                  154 non-null    float64
 33  restoregoal_lta_ha            154 non-null    float64
 34  restoregoal_80th_ha           154 non-null    float64
 35  protectgoal_lta_ha            154 non-null    float64
 36  protectgoal_80th_ha           154 non-null    float64
dtypes: float64(31), geometry(1), object(5)
memory usage: 44.6+ KB

In [ ]:
df.drop_duplicates(inplace=True)
df.shape

(3644, 26)

In [ ]:
df[df.species=='All'][['WATERSHED_CODE','surpdef_lta_kcal','surpdef_80th_kcal']]

In [ ]:
dbl_df = df[df.duplicated('WATERSHED_CODE', keep=False)]
dbl_df.shape

(2490, 26)

In [ ]:
df2 = dbl_df.groupby('WATERSHED_CODE').agg({'tothabitat_kcal':len})
df2.loc[:,'tothabitat_kcal_min'] = dbl_df.groupby('WATERSHED_CODE').agg({'tothabitat_kcal':min}).tothabitat_kcal
df2.loc[:,'tothabitat_kcal_max'] = dbl_df.groupby('WATERSHED_CODE').agg({'tothabitat_kcal':max}).tothabitat_kcal
del dbl_df
df2

C:\Users\akreiger\AppData\Local\Temp\ipykernel_23520\1839641141.py:2: FutureWarning: The provided callable <built-in function min> is currently using SeriesGroupBy.min. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "min" instead.
  df2.loc[:,'tothabitat_kcal_min'] = dbl_df.groupby('WATERSHED_CODE').agg({'tothabitat_kcal':min}).tothabitat_kcal
C:\Users\akreiger\AppData\Local\Temp\ipykernel_23520\1839641141.py:3: FutureWarning: The provided callable <built-in function max> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df2.loc[:,'tothabitat_kcal_max'] = dbl_df.groupby('WATERSHED_CODE').agg({'tothabitat_kcal':max}).tothabitat_kcal

                tothabitat_kcal  tothabitat_kcal_min  tothabitat_kcal_max
WATERSHED_CODE
BF02392                       2         7.977262e+07         7.977262e+07
BF02394                       2         3.505143e+09         3.505143e+09
BF02397                       2         4.327015e+08         4.327015e+08
BF02398                       2         4.281310e+03         4.281310e+03
BF02401                       2         7.928983e+07         7.928983e+07
...                         ...                  ...                  ...
QC0980                        2         3.262952e+07         3.262952e+07
QC0986                        2         3.072110e+08         3.072110e+08
QC0987                        2         6.198402e+07         6.198402e+07
QC0988                        2         2.759903e+08         2.759903e+08
QC099                         2         3.243846e+08         3.243846e+08

[1245 rows x 3 columns]

In [ ]:
df2[abs(df2.tothabitat_kcal_min-df2.tothabitat_kcal_max)>1]

Empty DataFrame
Columns: [tothabitat_kcal, tothabitat_kcal_min, tothabitat_kcal_max]
Index: []

In [ ]:
df.drop_duplicates(subset='WATERSHED_CODE', inplace=True)
df.shape

(2399, 26)

In [ ]:
df.info()

<class 'geopandas.geodataframe.GeoDataFrame'>
Index: 2399 entries, 0 to 3668
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   WATERSHED_CODE       2399 non-null   object
 1   WATERSHED_CODE_ha    2399 non-null   float64
 2   code                 1764 non-null   object
 3   dud_lta              2399 non-null   float64
 4   demand_lta_kcal      2399 non-null   float64
 5   popobj_lta           2399 non-null   float64
 6   dud_80th             2399 non-null   float64
 7   demand_80th_kcal     2399 non-null   float64
 8   popobj_80th          2399 non-null   float64
 9   tothabitat_kcal      2399 non-null   float64
 10  protected_kcal       2399 non-null   float64
 11  protectedhabitat_ha  2399 non-null   float64
 12  urbanHa              2399 non-null   float64
 13  urbanNrgy            2399 non-null   float64
 14  unavailha            2399 non-null   float64
 15  surpdef_lta_kcal     2399 non-null   float64
 16  surpdef_80th_kcal    2399 non-null   float64
 17  nrgprot_lta_kcal     2399 non-null   float64
 18  nrgprot_80th_kcal    2399 non-null   float64
 19  wtMean_kcal_per_ha   2373 non-null   float64
 20  available_ha         2399 non-null   float64
 21  geometry             2399 non-null   geometry
 22  restoregoal_lta_ha   2399 non-null   float64
 23  restoregoal_80th_ha  2399 non-null   float64
 24  protectgoal_lta_ha   2399 non-null   float64
 25  protectgoal_80th_ha  2399 non-null   float64
dtypes: float64(23), geometry(1), object(2)
memory usage: 506.0+ KB

In [ ]:
### CALCULATE STANDARDIZED ABDU FIELDS

# demand_norm = 'abdu_demand_norm'
# restore_norm = 'restore_goal_norm'
# protect_norm = 'protect_goal_norm'
abdu_restore = 'abdu_norm_restoregoal_80th'
abdu_protect = 'abdu_norm_protectgoal_80th'

# Replace nulls with 0 (shouldn't pre-exist)
df.loc[:,'abdu_demand_80th_kcal'] = df.abdu_demand_80th_kcal.fillna(0)
df.loc[:,'restoregoal_80th_ha'] = df.restoregoal_80th_ha.fillna(0)
df.loc[:,'protectgoal_80th_ha'] = df.protectgoal_80th_ha.fillna(0)

# Get min-max values
minVal_demand, maxVal_demand = df.abdu_demand_80th_kcal.min(), df.abdu_demand_80th_kcal.max()
minVal_restore, maxVal_restore = df.restoregoal_80th_ha.min(), df.restoregoal_80th_ha.max()
minVal_protect, maxVal_protect = df.protectgoal_80th_ha.min(), df.protectgoal_80th_ha.max()

# normalized demand for black ducks
zval_demand = (df.abdu_demand_80th_kcal-minVal_demand)/(maxVal_demand-minVal_demand)
# normalized restoration value for all dabbling ducks
zval_restore = (df.restoregoal_80th_ha-minVal_restore)/(maxVal_restore-minVal_restore)
# normalized protection value for all dabbling ducks
zval_protect = (df.protectgoal_80th_ha-minVal_protect)/(maxVal_protect-minVal_protect)
# normalized restoration goal for black ducks
df.loc[:, abdu_restore] = zval_demand * zval_restore
# normalized protection goal for black ducks
df.loc[:, abdu_protect] = zval_demand * zval_protect
# # normalized restoration goal
# df.loc[:, restore_norm] = zval_restore
# # normalized protection goal
# df.loc[:, protect_norm] = zval_protect

In [ ]:
import pandas as pd
df2 = pd.concat([df.iloc[:,:21],df.iloc[:,22:],df.iloc[:,21]], ignore_index=True, axis=1)

In [ ]:
flds = df.columns[:21].to_list()
flds.extend(df.columns[22:].to_list())
flds.append(df.columns[21])
flds

['WATERSHED_CODE',
 'WATERSHED_CODE_ha',
 'code',
 'dud_lta',
 'demand_lta_kcal',
 'popobj_lta',
 'dud_80th',
 'demand_80th_kcal',
 'popobj_80th',
 'tothabitat_kcal',
 'protected_kcal',
 'protectedhabitat_ha',
 'urbanHa',
 'urbanNrgy',
 'unavailha',
 'surpdef_lta_kcal',
 'surpdef_80th_kcal',
 'nrgprot_lta_kcal',
 'nrgprot_80th_kcal',
 'wtMean_kcal_per_ha',
 'available_ha',
 'restoregoal_lta_ha',
 'restoregoal_80th_ha',
 'protectgoal_lta_ha',
 'protectgoal_80th_ha',
 'geometry']

In [ ]:
df2 = df2.set_axis(flds, axis=1)
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2399 entries, 0 to 3668
Data columns (total 26 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   WATERSHED_CODE       2399 non-null   object
 1   WATERSHED_CODE_ha    2399 non-null   float64
 2   code                 1764 non-null   object
 3   dud_lta              2399 non-null   float64
 4   demand_lta_kcal      2399 non-null   float64
 5   popobj_lta           2399 non-null   float64
 6   dud_80th             2399 non-null   float64
 7   demand_80th_kcal     2399 non-null   float64
 8   popobj_80th          2399 non-null   float64
 9   tothabitat_kcal      2399 non-null   float64
 10  protected_kcal       2399 non-null   float64
 11  protectedhabitat_ha  2399 non-null   float64
 12  urbanHa              2399 non-null   float64
 13  urbanNrgy            2399 non-null   float64
 14  unavailha            2399 non-null   float64
 15  surpdef_lta_kcal     2399 non-null   float64
 16  surpdef_80th_kcal    2399 non-null   float64
 17  nrgprot_lta_kcal     2399 non-null   float64
 18  nrgprot_80th_kcal    2399 non-null   float64
 19  wtMean_kcal_per_ha   2373 non-null   float64
 20  available_ha         2399 non-null   float64
 21  restoregoal_lta_ha   2399 non-null   float64
 22  restoregoal_80th_ha  2399 non-null   float64
 23  protectgoal_lta_ha   2399 non-null   float64
 24  protectgoal_80th_ha  2399 non-null   float64
 25  geometry             2399 non-null   geometry
dtypes: float64(23), geometry(1), object(2)
memory usage: 506.0+ KB

In [ ]:
sr = arcpy.SpatialReference(102008)
sr

In [ ]:
# arcpy.Delete_management(out_fc)
arcpy.CreateFeatureclass_management(os.path.dirname(out_fc), os.path.basename(out_fc), "POLYGON", spatial_reference=sr)

In [ ]:
df = df2.copy()

In [ ]:
flds = []
for c in df.columns:
    f = [c]
    if df[c].dtype == 'object':
        f.extend(['TEXT',c,max([len(str(i)) for i in df[c].values])])
    elif df[c].dtype in ['int64', 'int32']:
        f.append('LONG')
    elif df[c].dtype in ['float64', 'float32']:
        f.append('FLOAT')
    else:
        pass
    print(f)
    if len(f)>1:
        flds.append(f)
len(flds)

['WATERSHED_CODE', 'TEXT', 'WATERSHED_CODE', 7]
['WATERSHED_CODE_ha', 'FLOAT']
['code', 'TEXT', 'code', 4]
['dud_lta', 'FLOAT']
['demand_lta_kcal', 'FLOAT']
['popobj_lta', 'FLOAT']
['dud_80th', 'FLOAT']
['demand_80th_kcal', 'FLOAT']
['popobj_80th', 'FLOAT']
['tothabitat_kcal', 'FLOAT']
['protected_kcal', 'FLOAT']
['protectedhabitat_ha', 'FLOAT']
['urbanHa', 'FLOAT']
['urbanNrgy', 'FLOAT']
['unavailha', 'FLOAT']
['surpdef_lta_kcal', 'FLOAT']
['surpdef_80th_kcal', 'FLOAT']
['nrgprot_lta_kcal', 'FLOAT']
['nrgprot_80th_kcal', 'FLOAT']
['wtMean_kcal_per_ha', 'FLOAT']
['available_ha', 'FLOAT']
['restoregoal_lta_ha', 'FLOAT']
['restoregoal_80th_ha', 'FLOAT']
['protectgoal_lta_ha', 'FLOAT']
['protectgoal_80th_ha', 'FLOAT']
['geometry']

25

In [ ]:
arcpy.AddFields_management(out_fc, flds)

In [ ]:
flds = [i[0] for i in flds]
flds.append('SHAPE@')
flds

['WATERSHED_CODE',
 'WATERSHED_CODE_ha',
 'code',
 'dud_lta',
 'demand_lta_kcal',
 'popobj_lta',
 'dud_80th',
 'demand_80th_kcal',
 'popobj_80th',
 'tothabitat_kcal',
 'protected_kcal',
 'protectedhabitat_ha',
 'urbanHa',
 'urbanNrgy',
 'unavailha',
 'surpdef_lta_kcal',
 'surpdef_80th_kcal',
 'nrgprot_lta_kcal',
 'nrgprot_80th_kcal',
 'wtMean_kcal_per_ha',
 'available_ha',
 'restoregoal_lta_ha',
 'restoregoal_80th_ha',
 'protectgoal_lta_ha',
 'protectgoal_80th_ha',
 'SHAPE@']

In [ ]:
with arcpy.da.InsertCursor(out_fc, flds) as cursor:
    for i in df.itertuples(index=False):
        row = list(i)
        row[-1] = arcpy.FromWKT(row[-1].wkt, sr)
        cursor.insertRow(row)

In [ ]:
arcpy.GetCount_management(out_fc)